gfs-miner:
  release_hours: ["00", "06", "12", "18"]
  start_date: "2017-01-01"
  end_date: "2023-12-31"
  latitude: -7.929304270692605
  longitude: 112.51864705407577
  output_dir: "output/"
  celery_broker_url: "redis://localhost:6379/0"
  api_store:
    url: "https://gfs-miner.io/api/collections/gfs/records"